name: "Publish"

on:
  push:
    branches: [ develop ]
    tags:
      - '*'

jobs:
  publish:
    env:
      GOPATH: /go/src/github.com/asvoboda/golangtest
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: ./godelw docker build --verbose

    - name: Publish Snapshot
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: |
           docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
           ./godelw docker push --tags=snapshot

    - name: Publish Release
      if: startsWith( github.ref, 'refs/tags/')
      run: |
           docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
           ./godelw docker push --tags=latest,version
           ./godelw publish github \
               --api-url "$GITHUB_API_URL" \
               --token "$GITHUB_TOKEN" \
               --owner asvoboda \
               --repository golangtest
