name: "Verify"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  verify:
    env:
      working-directory: /go/src/github.com/asvoboda/golangtest
    name: Verify
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.16.x]

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run:|
        echo $GOPATH
        go test -v

    - name: Test
      run:|
        echo $GOPATH
        ./godelw verify --apply=false
